fix(LINGUIST-414): Update profile fix
LinguistAI/machine-learning pull request #33
Opened 2024-04-22 23:11 UTC by KardelenCeren

Minor fix to update profile - it was giving duplicate email error while updating and some json fields were broken

2024-04-22 23:13 UTC, can-aslan approved these changes
LGTM

2024-04-23 05:30 UTC, tolgaozgun requested changes
I didn't understand the changes, TextField is currently working.

2024-04-23 05:30 UTC, tolgaozgun commented on profiling/views/update_user_profile.py
Why is this change required? This file is for user service to update the ml service

2024-04-23 05:30 UTC, tolgaozgun commented on profiling/models.py
Why is this required? We are already using json.loads and json.dumps, the existing DB is not updated, hence your issues.

2024-04-23 07:47 UTC, closed without merging